# ANN

# Importing Libraries

In [1]:
import numpy as np
import tensorflow as tf
import pandas as pd
import math

In [ ]:
tf.__version__

'2.8.2'

# Part 1 - Data Preprocessing

Starting from column [3] to One before Last [ 3 : -1 ]

In [2]:
dataset = pd.read_csv('/content/Churn_Modelling.csv')
x = dataset.iloc[ : , 3:-1].values
y = dataset.iloc[ : , -1].values

In [3]:
print(x)

[[619 'France' 'Female' ... 1 1 101348.88]
 [608 'Spain' 'Female' ... 0 1 112542.58]
 [502 'France' 'Female' ... 1 0 113931.57]
 ...
 [709 'France' 'Female' ... 0 1 42085.58]
 [772 'Germany' 'Male' ... 1 0 92888.52]
 [792 'France' 'Female' ... 1 0 38190.78]]


In [ ]:
print(y)

[1 0 1 ... 1 1 0]


Label encoding : Gender

In [4]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
x[ : , 2] = le.fit_transform(x[ : , 2])

In [ ]:
print(x)

[[619 'France' 0 ... 1 1 101348.88]
 [608 'Spain' 0 ... 0 1 112542.58]
 [502 'France' 0 ... 1 0 113931.57]
 ...
 [709 'France' 0 ... 0 1 42085.58]
 [772 'Germany' 1 ... 1 0 92888.52]
 [792 'France' 0 ... 1 0 38190.78]]


Label encoding "Geography Column"

In [5]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer( transformers=[('encoder', OneHotEncoder(), [1])], remainder='passthrough')
x = np.array(ct.fit_transform(x))

In [ ]:
print(x)

[[1.0 0.0 0.0 ... 1 1 101348.88]
 [0.0 0.0 1.0 ... 0 1 112542.58]
 [1.0 0.0 0.0 ... 1 0 113931.57]
 ...
 [1.0 0.0 0.0 ... 0 1 42085.58]
 [0.0 1.0 0.0 ... 1 0 92888.52]
 [1.0 0.0 0.0 ... 1 0 38190.78]]


Splitting the dataset into Training set and Testing set

In [6]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y ,test_size = 0.2, random_state = 0)

Feature scaling

In [7]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train = sc.fit_transform(x_train)
x_test = sc.fit_transform(x_test)

# Part 2 - Building the ANN

Initializing the ANN

Tf contains Keras contains Models contains Sequential

ann is an object of type Sequential

In [8]:
ann = tf.keras.models.Sequential()

Adding the input layer and the first hidden layer

Dense() class is a hidden layer that takes all the nodes in previous layer as input

Parameters of Dense():

units -> number of nodes in the layer [Hyperparameter]

activation -> activation function

"relu" - rectification activation function"

"sigmoid" - sigmoid activation function" for Binary classification Output

"softmax" - for Multiclass classification Output

**Get Activation Functions**

**Get Layer Types**

In [9]:
ann.add( tf.keras.layers.Dense( units=6, activation='relu' ) )

Adding the second hidden layer

In [10]:
ann.add( tf.keras.layers.Dense( units=6, activation='relu' ) )

Adding the Output layer

The output is Binary outcome: so output units is 1

If outcome is Multiclass, eg n=3 We would need 3 output nodes

In [11]:
ann.add( tf.keras.layers.Dense( units=1, activation='sigmoid' ) )

# Part 3 - Training the ANN

Compiling the ANN

Compile()

Parameters:

optimizer = 

"adam" -> Stochastic Gradient Descent

loss = Loss Function

'binary_crossentropy' -> Binary classification

'categorical_crossentropy' -> Multi-class Classification

metrics = []

'accuracy' - Accuracy score

**Get Optimizers**

**Get Loss functions**

**Get Metrics**

In [12]:
ann.compile( optimizer="adam" , loss='binary_crossentropy'  , metrics=[ 'accuracy' ] )

Training the ANN on the Training set

batch_size -> number of rows in a Batch

epochs -> Iterations

In [13]:
ann.fit(x_train, y_train, batch_size=32, epochs=100 )

Epoch 1/100
250/250 [==============================] - 1s 2ms/step - loss: 0.5310 - accuracy: 0.7896
Epoch 2/100
250/250 [==============================] - 1s 2ms/step - loss: 0.4671 - accuracy: 0.7960
Epoch 3/100
250/250 [==============================] - 1s 2ms/step - loss: 0.4386 - accuracy: 0.7966
Epoch 4/100
250/250 [==============================] - 0s 2ms/step - loss: 0.4203 - accuracy: 0.8105
Epoch 5/100
250/250 [==============================] - 0s 2ms/step - loss: 0.4102 - accuracy: 0.8141
Epoch 6/100
250/250 [==============================] - 0s 2ms/step - loss: 0.4030 - accuracy: 0.8201
Epoch 7/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3963 - accuracy: 0.8253
Epoch 8/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3898 - accuracy: 0.8317
Epoch 9/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3840 - accuracy: 0.8361
Epoch 10/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3778 - accura

# Part 4 - Making the Predictions and evaluating the model

Make a Prediction:

Geography = France

Credit Score = 600

Gender = Male

Age = 40 yrs old

Tenure = 3 yrs

Balance = $60000

No of Products = 2

Credit Card = Yes

Active Member = yes

Estimated Salary = $50000

In [ ]:
print(ann.predict( sc.transform([[1, 0, 0, 600, 1, 40, 3, 60000, 2, 1, 1, 50000]] )) > 0.5 )

[[ True]]


1. Input of ANN is a 2D array

2. Encode France before Input

    First Three values => Code for France

3. Apply the same scaling. 

    Using sc.transform()

4. Output will be a Probability.

    Using Boolean Operator



Predicting the Test results

In [ ]:
y_pred = ann.predict(x_test)
y_pred = ( y_pred > 0.5 )
print(np.concatenate( 
                        (   y_pred.reshape( len(y_pred),1 ), 
                            y_test.reshape( len(y_test),1 ) 
                        ),
                        1 
                     )
      )

[[0 0]
 [0 1]
 [0 0]
 ...
 [0 0]
 [0 0]
 [0 0]]


Making the Confusion Matrix

In [ ]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[1528   67]
 [ 211  194]]


0.861

# Custom Activation Function

In [40]:
import keras.backend as K
from keras.layers import Activation
from keras.utils.generic_utils import get_custom_objects

def custom_activation(x):
  return K.maximum(K.zeros_like(x),tf.math.log(1+x))

In [41]:
custom8 = tf.keras.models.Sequential()
custom8.add( tf.keras.layers.Dense( units=6, activation=custom_activation ) )
custom8.add( tf.keras.layers.Dense( units=1, activation='sigmoid' ) )

In [42]:
custom8.compile( optimizer="adam" , loss='binary_crossentropy'  , metrics=[ 'accuracy' ] )
custom8.fit(x_train, y_train, batch_size=32, epochs=100 )

Epoch 1/100
250/250 [==============================] - 1s 2ms/step - loss: nan - accuracy: 0.7960
Epoch 2/100
250/250 [==============================] - 0s 2ms/step - loss: nan - accuracy: 0.7960
Epoch 3/100
250/250 [==============================] - 0s 2ms/step - loss: nan - accuracy: 0.7960
Epoch 4/100
250/250 [==============================] - 0s 2ms/step - loss: nan - accuracy: 0.7960
Epoch 5/100
250/250 [==============================] - 0s 2ms/step - loss: nan - accuracy: 0.7960
Epoch 6/100
250/250 [==============================] - 0s 2ms/step - loss: nan - accuracy: 0.7960
Epoch 7/100
250/250 [==============================] - 0s 2ms/step - loss: nan - accuracy: 0.7960
Epoch 8/100
250/250 [==============================] - 0s 2ms/step - loss: nan - accuracy: 0.7960
Epoch 9/100
250/250 [==============================] - 0s 2ms/step - loss: nan - accuracy: 0.7960
Epoch 10/100
250/250 [==============================] - 0s 2ms/step - loss: nan - accuracy: 0.7960
Epoch 11/100
250/25

In [43]:
y_pred = custom8.predict(x_test)
y_pred = ( y_pred > 0.5 )
print(np.concatenate( 
                        (   y_pred.reshape( len(y_pred),1 ), 
                            y_test.reshape( len(y_test),1 ) 
                        ),
                        1 
                     )
      )

from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

63/63 [==============================] - 0s 3ms/step
[[0 0]
 [0 1]
 [0 0]
 ...
 [0 0]
 [0 0]
 [0 0]]
[[1595    0]
 [ 405    0]]


0.7975